### ISSUE TITLE
header doesnt match figma (design)

### ISSUE THREAD

**Issue by papertek** [CamelliaCommunity/wiki-frontend#1]
in-site version
![image](https://github.com/CamelliaCommunity/wiki-frontend/assets/72106503/a65658bf-8e29-467a-b1fb-d0d7c85b6ef7)

figma version
![image](https://github.com/CamelliaCommunity/wiki-frontend/assets/72106503/2d27e11e-c7f1-48b5-94b5-bed9c15085c1)

as you can see it doesn't match the [figma](https://www.figma.com/file/MAtikPPpURkXzY9rd3glQk/Camellia-Wiki?type=design&node-id=1440%3A913&mode=design&t=CtZgANd0JBYppsBW-1) :(

**Comment by AyanoNK** [comment]
Fun things are fun. A bad header is not fun.

**Comment by papertek** [comment]
reopening because it still doesnt match (recent changes broke)

**Comment by papertek** [comment]
fixed
